### PR TITLE
Do not prepend rust macro calls with `&`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
New issue I encountered while working on `docs.rs`. :D

### CODE REVIEW

**Review by Kijewski — APPROVED** [review]
:+1:

**Comment by GuillaumeGomez** [comment]
Do you want other things to be merged before I make a new `0.3.4` release?

**Comment by Kijewski** [comment]
No, I have no ideas right now what I would like to add or change. :)

**Comment by GuillaumeGomez** [comment]
Ok, gonna make a new release then. I still want to push for setting run-time variables value. Would be nice to discuss about how it should look like (mostly in the templates, the generated code is easy to do hehe).

**Pull request merged**
