### PR TITLE
Add newly added f16 and f128 types in parsing

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
https://github.com/rust-lang/rust/issues/116909

### CODE REVIEW

**Review by Kijewski — CHANGES_REQUESTED** [review]
The change is fine. The compiler will tell the user that they can't use f128 just yet. 

But I don't like the current implementation, neither for int suffices nor float. IMO it would be better to capture an ident and match the result. This reduces the chance of false positive matches like 1_u321.

**Comment by GuillaumeGomez** [comment]
Ok, merging this one and opening an issue. Gonna give it a try. :)

**Comment by GuillaumeGomez** [comment]
Ah wait no, can't since you didn't approve. Gonna try in this PR then I suppose. :stuck_out_tongue:

**Review by Kijewski — APPROVED** [review]
Approved, because it's strictly better than before :)

**Comment by GuillaumeGomez** [comment]
Opening an issue then. ;)

**Pull request merged**
