### PR TITLE
readme: add reference to Rinja Playground

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Please also add it into the book. I think it really deserves as much attention as possible. I'll personally use it quite a lot. :D

**Comment by Kijewski** [comment]
Added. :)

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Again, great job! I really love this feature. :)

**Comment by Kijewski** [comment]
Thank you! :D

**Pull request merged**
