### PR TITLE
Fix clippy warnings in rust nightly 1.85

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Ah annoying. With newer rust version, the error output changed a bit (hence why CI is failing).

**Comment by Kijewski** [comment]
I added (and removed) a gate for different rust versions before: <https://github.com/rinja-rs/rinja/commit/5955ba23c172ef6bbc0116b9ab0d6f068b86a688>. But duplicating everything felt kinda wrong. Should we simply ignore nightly for now in the CI?

**Comment by GuillaumeGomez** [comment]
I think so yes. Or just run some tests, not ui ones.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
