### PR TITLE
Fix up #6: add missing file

### PR DESCRIPTION
**Pull request by Kijewski**
In #6 I forgot to add the most importand file of the PR: .readthedocs.yaml

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Just merge once CI is done. Also please take a look at https://github.com/rinja-rs/rinja/pull/6#issuecomment-2175598535.

**Comment by Kijewski** [comment]
I created the project [rinja](https://readthedocs.org/projects/rinja/). I tried to add you, @GuillaumeGomez, as an owner, but you don't seem to have an account. You can either create an account using an email address or through your github account. Just tell me your user name once you have created your account.

Normally RTD listens to github hooks, but I'm not allowed to configure the repo. Either you have to add the hooks or you have to authorize me. :)

**Comment by GuillaumeGomez** [comment]
I think I did. Tell me if it's not the case. The goal is for everyone to have all accesses.

**Comment by GuillaumeGomez** [comment]
In any case I created an account named `GuillaumeGomez` so you should be able to find me. ;)

**Comment by Kijewski** [comment]
Let's see if the hook works now!

**Pull request merged**
