### PR TITLE
Remove useless `indent` information from `Buffer`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
First real PR for this project. :)

### CODE REVIEW

**Comment by Kijewski** [comment]
Good call! Maybe we can later add a `prettyprint` feature to indent the generated code using [prettyplease](https://crates.io/crates/prettyplease], but I think that's very low on my TODO list.

With this change `Buffer::writeln` is infallible. Do you want to remove the Result type result?

**Comment by GuillaumeGomez** [comment]
Good call, let's remove it. :)

**Comment by GuillaumeGomez** [comment]
Done!

**Review by Kijewski — APPROVED** [review]
Nice! Much easier to read.

**Comment by Kijewski** [comment]
Thanks! I have a "merge" button now, but I don't have the privileges to add hooks.

**Comment by GuillaumeGomez** [comment]
Let me fix that. :)

**Pull request merged**
